import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()
  const [name, setName] = useState()

  const handleChange = (e) => {
    setName(e.target.value)
  }

  const handleLogin = () => {
    fetch('/api/login', {
      method: 'POST',
      headers:{
        'content-type': 'application/json',
      },
      body: JSON.stringify({ name })
    }).then(response => {
      router.push('/search')
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Next
        </h1>
        <div>
          <input type="text" placeholder='name' style={{ marginRight: '0.5rem' }} onChange={handleChange} />
          <button onClick={handleLogin}>Login</button>
        </div>
      </main>
    </div>
  )
}
